id: P6DD7575A
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG6290
  instance_id: http://purl.bdrc.io/resource/IE1KG6290
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - དཔག་བསམ་དབང་པོའི་སྐྱེས་རབས་ཀྱི་འཕྲེང་བ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P888
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    6bc250ce46e7455683aab4cdd11aaa8e:
      title: པོད ༡་དཔག་བསམ་དབང་པོའི་སྐྱེས་རབས་ཀྱི་འཕྲེང་བ།
      volume_number: 1
      base_file: UT1KG6290_I1KG6321_0000.txt
      reference: http://purl.bdrc.io/resource/VLB7DCF3DDDD353A3A
      image_group: I1KG6321
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG6290
  - http://purl.bdrc.io/resource/W1KG6290
  ocr_software: Namsel
created_at: '2021-12-22T10:59:13.599405'
last_modified_at: '2021-12-22T10:59:13.599411'
